# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hpxuan的博客
email: hpx12138@126.com
description:  其实当站在人生岔路口的时候，每个人都会做出最终抉择。无论选择哪条路，
                多年之后回头再看，都会觉得后悔。
                因为没有人知道选择另一条路会有什么结果，也不可能知道！！！
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  hpxuan

# Build settings
markdown: kramdown
