
title: hpxuan
email: hpx12138@126.com
description: 规则，分天道规则和人道规则。清泉自高往低而流，日月星辰东升西落，
                此乃天道规则，非人力所不能及也。吾辈亦不奢望。
baseurl: "/hpxuan.github.io"
url: "http://www.hpxuan.com"
twitter_username: hpxuan
github_username:  hpxuan

 
markdown: kramdown
