# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hpxuan
email: hpx12138@126.com
description: 规则，分天道规则和人道规则。清泉自高往低而流，日月星辰东升西落，
                此乃天道规则，非人力所不能及也。吾辈亦不奢望。
baseurl: "/hpxuan.github.io" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hpxuan
github_username:  hpxuan

# Build settings
markdown: kramdown
